[workspace]
members = ["crates/*", "tests/test-crate"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
askama = { version = "0.16.0", features = ["with-num-traits"] }
cargo_metadata = { version = "0.23.1" }
dashmap = { version = "6.2.1" }
facet = { version = "0.46.5" }
facet-error = { version = "0.46.5" }
figue = { version = "4.0.4" }
heck = { version = "0.5.0" }
indicatif = { version = "0.18.4" }
postcard = { version = "1.1.3", features = ["use-std"] }
prettyplease = { version = "0.2" }
quote = { version = "1.0" }
rustdoc-types = { version = "0.57.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
thiserror = { version = "2.0" }
tracing = { version = "0.1" }
tracing-indicatif = { version = "0.3" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

koffi = { path = "crates/core" }
koffi-bindgen = { path = "crates/bindgen" }
koffi-build = { path = "crates/build" }
koffi-ir = { path = "crates/ir" }
koffi-macros = { path = "crates/macros" }
koffi-runtime = { path = "crates/runtime" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# cargo = { level = "warn", priority = -1 }
# restriction = { level = "warn", priority = -1 }

# unwrap_used = "warn"
doc_paragraphs_missing_punctuation = "warn"

# nursery
use_self = "allow"
option_if_let_else = "allow"

# pedantic
missing_errors_doc = "allow"
too_many_lines = "allow"
match_same_arms = "allow"
format_push_string = "allow"
redundant_closure_for_method_calls = "allow"
used_underscore_items = "allow"
