[workspace]
members = ["crates/*", "examples/*", "tests"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = { version = "1.0" }
askama = { version = "0.16.0", features = ["full"] }
cargo_metadata = { version = "0.23.1" }
crossterm = { version = "0.29.0" }
dashmap = { version = "6.2.1" }
dirs = { version = "6.0.0" }
rustc-hash = { version = "2.1.3" }
facet = { version = "0.50.0-rc.5" }
facet-format = { version = "0.50.0-rc.5" }
facet-json = { version = "0.50.0-rc.5" }
facet-pretty = { version = "0.50.0-rc.5" }
figue = { version = "5.0.0-rc.5" }
heck = { version = "0.5.0" }
object = { version = "0.39.1" }
camino = { version = "1.2.4" }
libloading = { version = "0.9.0" }
indicatif = { version = "0.18.4" }
indoc = { version = "2.0.7" }
insta = { version = "1.48.0" }
pathdiff = { version = "0.2.3" }
postcard = { version = "1.1.3", features = ["use-std"] }
prettyplease = { version = "0.2" }
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = { version = "1.0" }
rustdoc-types = { version = "0.57.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
syntect = { version = "5.3.0" }
thiserror = { version = "2.0" }
toml = { version = "1.1.2" }
tracing = { version = "0.1" }
tracing-indicatif = { version = "0.3" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
vscode-theme-syntect = { version = "0.1.1" }
walkdir = { version = "2.5.0" }

koffi = { path = "crates/api" }
koffi-build = { path = "crates/build" }
koffi-codegen = { path = "crates/codegen" }
koffi-core = { path = "crates/core" }
koffi-macros = { path = "crates/macros" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# cargo = { level = "warn", priority = -1 }
# restriction = { level = "warn", priority = -1 }

unwrap_used = "warn"

# nursery
use_self = "allow"
option_if_let_else = "allow"

# pedantic
missing_errors_doc = "allow"
missing_panics_doc = "allow"
too_many_lines = "allow"
match_same_arms = "allow"
format_push_string = "allow"
redundant_closure_for_method_calls = "allow"
used_underscore_items = "allow"
manual_let_else = "allow"
map_unwrap_or = "allow"
