use std::path::PathBuf;

use facet::Facet;
use figue::{
    self as args, ConfigFormat, ConfigFormatError, ConfigValue, FigueBuiltins, JsoncFormat,
};
use koffi_build::{OutputDirs, build_and_stage, build_crate, config::KoffiConfig};
use koffi_codegen::{extract::extract_schema, generator};
use tracing::{Level, debug, info};

#[derive(Facet, Debug)]
pub struct Cli {
    #[facet(args::subcommand)]
    pub command: Command,

    /// Verbose logging (debug level).
    #[facet(args::named, args::short = 'v')]
    pub verbose: bool,

    /// --help / --version / --completions, for free.
    #[facet(flatten)]
    pub builtins: FigueBuiltins,

    #[facet(args::config)]
    pub config: KoffiConfig,
}

#[repr(u8)]
#[derive(Facet, Debug)]
pub enum Command {
    /// Package artifacts.
    #[facet(rename = "pack")]
    Package(PackageArgs),

    /// Generate bindings.
    #[facet(rename = "gen")]
    Generate(PackageArgs),
}

#[derive(Facet, Debug)]
pub struct PackageArgs {
    /// Path to Rust crate root (Cargo.toml directory).
    #[facet(args::positional, default = ".")]
    pub crate_path: PathBuf,

    /// Output directory.
    #[facet(args::named, args::short = 'o', default = "generated")]
    pub out: PathBuf,

    /// Build in release mode: the source crate `gen` builds to extract its
    /// schema, and the staged glue libs `pack` produces (jvm, android and
    /// native targets all follow).
    #[facet(args::named, args::short = 'r')]
    pub release: bool,

    /// Rerun on Rust source changes.
    #[facet(args::named, args::short = 'w')]
    pub watch: bool,

    /// Treat warnings as errors and abort generation if any are found.
    #[facet(args::named, args::short = 'D')]
    pub deny_warnings: bool,
}

fn main() -> anyhow::Result<()> {
    // The `--config <path>` flag is auto-generated by figue, but its targeted
    // file path double-nests the config root and silently loses values to the
    // field defaults (figue 5.0.0-rc.5 quirk). Preload the file ourselves and
    // feed it through the content path, which handles root-keyed files; the
    // auto flag still parses (its value is consumed), so nothing else changes.
    let config = figue::builder::<Cli>()
        .expect("failed to build the figue config")
        .file(|f| {
            match preload_config_file() {
                Some((contents, name)) => {
                    f.content(contents, name)
                        .format(TomlFormat)
                        .format(JsoncFormat)
                }
                None => {
                    f.default_paths(["./koffi.toml", "./koffi.jsonc", "./koffi.json"])
                        .format(TomlFormat)
                        .format(JsoncFormat)
                }
            }
        })
        .cli(|cli| cli)
        .build();
    let cli = figue::Driver::new(config)
        .run()
        .into_result()
        .map_err(|e| anyhow::anyhow!("{e}"))?
        .get();

    tracing_subscriber::fmt()
        .with_max_level(if cli.verbose {
            Level::DEBUG
        } else {
            Level::INFO
        })
        .init();

    match cli.command {
        Command::Package(args) => {
            let (dirs, crate_ident) = generate(&args, &cli.config)?;

            info!("packaging the generated glue crate");
            build_and_stage(&dirs, &crate_ident, &cli.config, args.release)?;
            info!("packaging completed successfully");
        }
        Command::Generate(args) => {
            generate(&args, &cli.config)?;
        }
    }

    Ok(())
}

/// Reads the config file named by `--config <path>` (or `--config=<path>`)
/// from the raw argv, returning its contents and the path used to pick the
/// format by extension. A missing file falls back to the default paths so
/// figue reports the error with its own diagnostics.
fn preload_config_file() -> Option<(String, String)> {
    let mut args = std::env::args().skip(1);
    while let Some(arg) = args.next() {
        let path = if let Some(path) = arg.strip_prefix("--config=") {
            path.to_string()
        } else if arg == "--config" {
            args.next()?
        } else {
            continue;
        };

        let contents = std::fs::read_to_string(&path).ok()?;

        return Some((contents, path));
    }

    None
}

fn generate(args: &PackageArgs, config: &KoffiConfig) -> anyhow::Result<(OutputDirs, String)> {
    let (crate_name, cdylib_path) = build_crate(&args.crate_path, args.release, &[], None)?;
    info!("generating code for {crate_name}");

    debug!("extracting schema from {}", cdylib_path.display());
    let schema = extract_schema(&crate_name, &cdylib_path)?;

    let dirs = OutputDirs {
        crate_path: args.crate_path.clone(),
        rust_out_dir: args.out.join("rust"),
        kotlin_out_dir: args.out.join("kotlin"),
    };

    generator::render_all(&schema, &dirs, config)?;
    info!("code generation completed successfully");

    Ok((dirs, crate_name))
}

/// figue's built-in formats cover JSON and JSONC; TOML goes through
/// facet-toml, which parses straight into figue's `ConfigValue` (the same
/// `FormatDeserializer` machinery facet-json uses).
pub struct TomlFormat;

impl ConfigFormat for TomlFormat {
    fn extensions(&self) -> &[&str] {
        &["toml"]
    }

    fn parse(&self, contents: &str) -> Result<ConfigValue, ConfigFormatError> {
        facet_toml::from_str(contents).map_err(|e| ConfigFormatError::new(e.to_string()))
    }
}
