package rs.koffi

/**
 * Base interface for all handles referencing opaque Rust types.
 */
interface KoffiHandle : AutoCloseable {
    val handleId: Long
    val isClosed: Boolean
}

/**
 * Global runtime settings and hooks for Koffi.
 */
object KoffiRuntime {
    /**
     * Hook used by Kotlin/Native and WASM to invoke the FFI handle release function.
     * This decouples the runtime library from the generated cinterop package names.
     */
    var releaseHandle: ((Long) -> Unit)? = null
}

/**
 * Base class that target-specific handles inherit from. Handles the lifecycle
 * and GC/finalizer tracking for the underlying Rust resource.
 */
expect abstract class KoffiHandleBase(handleId: Long) : KoffiHandle {
    override val handleId: Long

    final override var isClosed: Boolean
        private set

    override fun close()
}

/**
 * Base class for all errors generated by Koffi.
 */
abstract class KoffiError : Exception()

/**
 * Represents a Rust panic caught at the FFI boundary.
 */
class KoffiPanic(override val message: String) : KoffiError()

/**
 * Thrown when trying to invoke a method on a closed handle.
 */
class KoffiHandleClosedException(message: String = "Handle has been closed") : Exception(message)

/**
 * Sealed class representing either a success value or a KoffiError.
 */
sealed class KoffiResult<out T, out E : KoffiError> {
    data class Ok<out T>(val value: T) : KoffiResult<T, Nothing>()
    data class Err<out E : KoffiError>(val error: E) : KoffiResult<Nothing, E>()

    fun getOrThrow(): T = when (this) {
        is Ok -> value
        is Err -> throw error
    }

    inline fun <R> fold(
        onOk: (T) -> R,
        onErr: (E) -> R
    ): R = when (this) {
        is Ok -> onOk(value)
        is Err -> onErr(error)
    }
}
