[package]
name = "example-project"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
serde.workspace = true

koffi.workspace = true
koffi-macros.workspace = true
koffi-runtime.workspace = true

[package.metadata.koffi]
namespace = "rs.koffi.example"
target-platforms = ["jvm", "mingwX64"]
